/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.core.web.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * ExecutionRequestResource
 */


public class ExecutionRequestResource {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("executionTestResult")
  private ExecutionTestResultResource executionTestResult = null;

  @JsonProperty("object")
  private TestObjectResource object = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("abnormal")
  private Boolean abnormal = null;

  @JsonProperty("percentAbnormal")
  private Double percentAbnormal = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("method")
  private String method = null;

  @JsonProperty("statusText")
  private String statusText = null;

  @JsonProperty("time")
  private Long time = null;

  @JsonProperty("size")
  private Long size = null;

  @JsonProperty("uploadFile")
  private UploadFileResource uploadFile = null;

  @JsonProperty("startedAt")
  private OffsetDateTime startedAt = null;

  public ExecutionRequestResource id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ExecutionRequestResource executionTestResult(ExecutionTestResultResource executionTestResult) {
    this.executionTestResult = executionTestResult;
    return this;
  }

   /**
   * Get executionTestResult
   * @return executionTestResult
  **/
  @Schema(description = "")
  public ExecutionTestResultResource getExecutionTestResult() {
    return executionTestResult;
  }

  public void setExecutionTestResult(ExecutionTestResultResource executionTestResult) {
    this.executionTestResult = executionTestResult;
  }

  public ExecutionRequestResource object(TestObjectResource object) {
    this.object = object;
    return this;
  }

   /**
   * Get object
   * @return object
  **/
  @Schema(description = "")
  public TestObjectResource getObject() {
    return object;
  }

  public void setObject(TestObjectResource object) {
    this.object = object;
  }

  public ExecutionRequestResource status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public ExecutionRequestResource abnormal(Boolean abnormal) {
    this.abnormal = abnormal;
    return this;
  }

   /**
   * Get abnormal
   * @return abnormal
  **/
  @Schema(description = "")
  public Boolean isAbnormal() {
    return abnormal;
  }

  public void setAbnormal(Boolean abnormal) {
    this.abnormal = abnormal;
  }

  public ExecutionRequestResource percentAbnormal(Double percentAbnormal) {
    this.percentAbnormal = percentAbnormal;
    return this;
  }

   /**
   * Get percentAbnormal
   * @return percentAbnormal
  **/
  @Schema(description = "")
  public Double getPercentAbnormal() {
    return percentAbnormal;
  }

  public void setPercentAbnormal(Double percentAbnormal) {
    this.percentAbnormal = percentAbnormal;
  }

  public ExecutionRequestResource url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public ExecutionRequestResource method(String method) {
    this.method = method;
    return this;
  }

   /**
   * Get method
   * @return method
  **/
  @Schema(description = "")
  public String getMethod() {
    return method;
  }

  public void setMethod(String method) {
    this.method = method;
  }

  public ExecutionRequestResource statusText(String statusText) {
    this.statusText = statusText;
    return this;
  }

   /**
   * Get statusText
   * @return statusText
  **/
  @Schema(description = "")
  public String getStatusText() {
    return statusText;
  }

  public void setStatusText(String statusText) {
    this.statusText = statusText;
  }

  public ExecutionRequestResource time(Long time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @Schema(description = "")
  public Long getTime() {
    return time;
  }

  public void setTime(Long time) {
    this.time = time;
  }

  public ExecutionRequestResource size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @Schema(description = "")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public ExecutionRequestResource uploadFile(UploadFileResource uploadFile) {
    this.uploadFile = uploadFile;
    return this;
  }

   /**
   * Get uploadFile
   * @return uploadFile
  **/
  @Schema(description = "")
  public UploadFileResource getUploadFile() {
    return uploadFile;
  }

  public void setUploadFile(UploadFileResource uploadFile) {
    this.uploadFile = uploadFile;
  }

  public ExecutionRequestResource startedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
    return this;
  }

   /**
   * Get startedAt
   * @return startedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecutionRequestResource executionRequestResource = (ExecutionRequestResource) o;
    return Objects.equals(this.id, executionRequestResource.id) &&
        Objects.equals(this.executionTestResult, executionRequestResource.executionTestResult) &&
        Objects.equals(this.object, executionRequestResource.object) &&
        Objects.equals(this.status, executionRequestResource.status) &&
        Objects.equals(this.abnormal, executionRequestResource.abnormal) &&
        Objects.equals(this.percentAbnormal, executionRequestResource.percentAbnormal) &&
        Objects.equals(this.url, executionRequestResource.url) &&
        Objects.equals(this.method, executionRequestResource.method) &&
        Objects.equals(this.statusText, executionRequestResource.statusText) &&
        Objects.equals(this.time, executionRequestResource.time) &&
        Objects.equals(this.size, executionRequestResource.size) &&
        Objects.equals(this.uploadFile, executionRequestResource.uploadFile) &&
        Objects.equals(this.startedAt, executionRequestResource.startedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, executionTestResult, object, status, abnormal, percentAbnormal, url, method, statusText, time, size, uploadFile, startedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecutionRequestResource {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    executionTestResult: ").append(toIndentedString(executionTestResult)).append("\n");
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    abnormal: ").append(toIndentedString(abnormal)).append("\n");
    sb.append("    percentAbnormal: ").append(toIndentedString(percentAbnormal)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    statusText: ").append(toIndentedString(statusText)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    uploadFile: ").append(toIndentedString(uploadFile)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
