/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.core.web.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * ExecutionTestCaseResource
 */


public class ExecutionTestCaseResource {
  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    PASSED("PASSED"),
    FAILED("FAILED"),
    ERROR("ERROR"),
    INCOMPLETE("INCOMPLETE"),
    RUNNING("RUNNING"),
    SKIPPED("SKIPPED"),
    NOT_RUN("NOT_RUN");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("startTime")
  private OffsetDateTime startTime = null;

  @JsonProperty("endTime")
  private OffsetDateTime endTime = null;

  @JsonProperty("duration")
  private Long duration = null;

  @JsonProperty("elapsedDuration")
  private Long elapsedDuration = null;

  @JsonProperty("totalTests")
  private Long totalTests = null;

  @JsonProperty("totalPassedTests")
  private Long totalPassedTests = null;

  @JsonProperty("totalFailedTests")
  private Long totalFailedTests = null;

  @JsonProperty("totalErrorTests")
  private Long totalErrorTests = null;

  @JsonProperty("totalIncompleteTests")
  private Long totalIncompleteTests = null;

  @JsonProperty("totalDiffTests")
  private Long totalDiffTests = null;

  @JsonProperty("totalDiffPassedTests")
  private Long totalDiffPassedTests = null;

  @JsonProperty("totalDiffFailedTests")
  private Long totalDiffFailedTests = null;

  @JsonProperty("totalDiffErrorTests")
  private Long totalDiffErrorTests = null;

  @JsonProperty("totalDiffIncompleteTests")
  private Long totalDiffIncompleteTests = null;

  @JsonProperty("executionId")
  private Long executionId = null;

  @JsonProperty("executionOrder")
  private Long executionOrder = null;

  @JsonProperty("testCaseId")
  private Long testCaseId = null;

  @JsonProperty("projectId")
  private Long projectId = null;

  public ExecutionTestCaseResource status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public ExecutionTestCaseResource startTime(OffsetDateTime startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @Schema(description = "")
  public OffsetDateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }

  public ExecutionTestCaseResource endTime(OffsetDateTime endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @Schema(description = "")
  public OffsetDateTime getEndTime() {
    return endTime;
  }

  public void setEndTime(OffsetDateTime endTime) {
    this.endTime = endTime;
  }

  public ExecutionTestCaseResource duration(Long duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @Schema(description = "")
  public Long getDuration() {
    return duration;
  }

  public void setDuration(Long duration) {
    this.duration = duration;
  }

  public ExecutionTestCaseResource elapsedDuration(Long elapsedDuration) {
    this.elapsedDuration = elapsedDuration;
    return this;
  }

   /**
   * Get elapsedDuration
   * @return elapsedDuration
  **/
  @Schema(description = "")
  public Long getElapsedDuration() {
    return elapsedDuration;
  }

  public void setElapsedDuration(Long elapsedDuration) {
    this.elapsedDuration = elapsedDuration;
  }

  public ExecutionTestCaseResource totalTests(Long totalTests) {
    this.totalTests = totalTests;
    return this;
  }

   /**
   * Get totalTests
   * @return totalTests
  **/
  @Schema(description = "")
  public Long getTotalTests() {
    return totalTests;
  }

  public void setTotalTests(Long totalTests) {
    this.totalTests = totalTests;
  }

  public ExecutionTestCaseResource totalPassedTests(Long totalPassedTests) {
    this.totalPassedTests = totalPassedTests;
    return this;
  }

   /**
   * Get totalPassedTests
   * @return totalPassedTests
  **/
  @Schema(description = "")
  public Long getTotalPassedTests() {
    return totalPassedTests;
  }

  public void setTotalPassedTests(Long totalPassedTests) {
    this.totalPassedTests = totalPassedTests;
  }

  public ExecutionTestCaseResource totalFailedTests(Long totalFailedTests) {
    this.totalFailedTests = totalFailedTests;
    return this;
  }

   /**
   * Get totalFailedTests
   * @return totalFailedTests
  **/
  @Schema(description = "")
  public Long getTotalFailedTests() {
    return totalFailedTests;
  }

  public void setTotalFailedTests(Long totalFailedTests) {
    this.totalFailedTests = totalFailedTests;
  }

  public ExecutionTestCaseResource totalErrorTests(Long totalErrorTests) {
    this.totalErrorTests = totalErrorTests;
    return this;
  }

   /**
   * Get totalErrorTests
   * @return totalErrorTests
  **/
  @Schema(description = "")
  public Long getTotalErrorTests() {
    return totalErrorTests;
  }

  public void setTotalErrorTests(Long totalErrorTests) {
    this.totalErrorTests = totalErrorTests;
  }

  public ExecutionTestCaseResource totalIncompleteTests(Long totalIncompleteTests) {
    this.totalIncompleteTests = totalIncompleteTests;
    return this;
  }

   /**
   * Get totalIncompleteTests
   * @return totalIncompleteTests
  **/
  @Schema(description = "")
  public Long getTotalIncompleteTests() {
    return totalIncompleteTests;
  }

  public void setTotalIncompleteTests(Long totalIncompleteTests) {
    this.totalIncompleteTests = totalIncompleteTests;
  }

  public ExecutionTestCaseResource totalDiffTests(Long totalDiffTests) {
    this.totalDiffTests = totalDiffTests;
    return this;
  }

   /**
   * Get totalDiffTests
   * @return totalDiffTests
  **/
  @Schema(description = "")
  public Long getTotalDiffTests() {
    return totalDiffTests;
  }

  public void setTotalDiffTests(Long totalDiffTests) {
    this.totalDiffTests = totalDiffTests;
  }

  public ExecutionTestCaseResource totalDiffPassedTests(Long totalDiffPassedTests) {
    this.totalDiffPassedTests = totalDiffPassedTests;
    return this;
  }

   /**
   * Get totalDiffPassedTests
   * @return totalDiffPassedTests
  **/
  @Schema(description = "")
  public Long getTotalDiffPassedTests() {
    return totalDiffPassedTests;
  }

  public void setTotalDiffPassedTests(Long totalDiffPassedTests) {
    this.totalDiffPassedTests = totalDiffPassedTests;
  }

  public ExecutionTestCaseResource totalDiffFailedTests(Long totalDiffFailedTests) {
    this.totalDiffFailedTests = totalDiffFailedTests;
    return this;
  }

   /**
   * Get totalDiffFailedTests
   * @return totalDiffFailedTests
  **/
  @Schema(description = "")
  public Long getTotalDiffFailedTests() {
    return totalDiffFailedTests;
  }

  public void setTotalDiffFailedTests(Long totalDiffFailedTests) {
    this.totalDiffFailedTests = totalDiffFailedTests;
  }

  public ExecutionTestCaseResource totalDiffErrorTests(Long totalDiffErrorTests) {
    this.totalDiffErrorTests = totalDiffErrorTests;
    return this;
  }

   /**
   * Get totalDiffErrorTests
   * @return totalDiffErrorTests
  **/
  @Schema(description = "")
  public Long getTotalDiffErrorTests() {
    return totalDiffErrorTests;
  }

  public void setTotalDiffErrorTests(Long totalDiffErrorTests) {
    this.totalDiffErrorTests = totalDiffErrorTests;
  }

  public ExecutionTestCaseResource totalDiffIncompleteTests(Long totalDiffIncompleteTests) {
    this.totalDiffIncompleteTests = totalDiffIncompleteTests;
    return this;
  }

   /**
   * Get totalDiffIncompleteTests
   * @return totalDiffIncompleteTests
  **/
  @Schema(description = "")
  public Long getTotalDiffIncompleteTests() {
    return totalDiffIncompleteTests;
  }

  public void setTotalDiffIncompleteTests(Long totalDiffIncompleteTests) {
    this.totalDiffIncompleteTests = totalDiffIncompleteTests;
  }

  public ExecutionTestCaseResource executionId(Long executionId) {
    this.executionId = executionId;
    return this;
  }

   /**
   * Get executionId
   * @return executionId
  **/
  @Schema(description = "")
  public Long getExecutionId() {
    return executionId;
  }

  public void setExecutionId(Long executionId) {
    this.executionId = executionId;
  }

  public ExecutionTestCaseResource executionOrder(Long executionOrder) {
    this.executionOrder = executionOrder;
    return this;
  }

   /**
   * Get executionOrder
   * @return executionOrder
  **/
  @Schema(description = "")
  public Long getExecutionOrder() {
    return executionOrder;
  }

  public void setExecutionOrder(Long executionOrder) {
    this.executionOrder = executionOrder;
  }

  public ExecutionTestCaseResource testCaseId(Long testCaseId) {
    this.testCaseId = testCaseId;
    return this;
  }

   /**
   * Get testCaseId
   * @return testCaseId
  **/
  @Schema(description = "")
  public Long getTestCaseId() {
    return testCaseId;
  }

  public void setTestCaseId(Long testCaseId) {
    this.testCaseId = testCaseId;
  }

  public ExecutionTestCaseResource projectId(Long projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @Schema(description = "")
  public Long getProjectId() {
    return projectId;
  }

  public void setProjectId(Long projectId) {
    this.projectId = projectId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecutionTestCaseResource executionTestCaseResource = (ExecutionTestCaseResource) o;
    return Objects.equals(this.status, executionTestCaseResource.status) &&
        Objects.equals(this.startTime, executionTestCaseResource.startTime) &&
        Objects.equals(this.endTime, executionTestCaseResource.endTime) &&
        Objects.equals(this.duration, executionTestCaseResource.duration) &&
        Objects.equals(this.elapsedDuration, executionTestCaseResource.elapsedDuration) &&
        Objects.equals(this.totalTests, executionTestCaseResource.totalTests) &&
        Objects.equals(this.totalPassedTests, executionTestCaseResource.totalPassedTests) &&
        Objects.equals(this.totalFailedTests, executionTestCaseResource.totalFailedTests) &&
        Objects.equals(this.totalErrorTests, executionTestCaseResource.totalErrorTests) &&
        Objects.equals(this.totalIncompleteTests, executionTestCaseResource.totalIncompleteTests) &&
        Objects.equals(this.totalDiffTests, executionTestCaseResource.totalDiffTests) &&
        Objects.equals(this.totalDiffPassedTests, executionTestCaseResource.totalDiffPassedTests) &&
        Objects.equals(this.totalDiffFailedTests, executionTestCaseResource.totalDiffFailedTests) &&
        Objects.equals(this.totalDiffErrorTests, executionTestCaseResource.totalDiffErrorTests) &&
        Objects.equals(this.totalDiffIncompleteTests, executionTestCaseResource.totalDiffIncompleteTests) &&
        Objects.equals(this.executionId, executionTestCaseResource.executionId) &&
        Objects.equals(this.executionOrder, executionTestCaseResource.executionOrder) &&
        Objects.equals(this.testCaseId, executionTestCaseResource.testCaseId) &&
        Objects.equals(this.projectId, executionTestCaseResource.projectId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, startTime, endTime, duration, elapsedDuration, totalTests, totalPassedTests, totalFailedTests, totalErrorTests, totalIncompleteTests, totalDiffTests, totalDiffPassedTests, totalDiffFailedTests, totalDiffErrorTests, totalDiffIncompleteTests, executionId, executionOrder, testCaseId, projectId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecutionTestCaseResource {\n");

    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    elapsedDuration: ").append(toIndentedString(elapsedDuration)).append("\n");
    sb.append("    totalTests: ").append(toIndentedString(totalTests)).append("\n");
    sb.append("    totalPassedTests: ").append(toIndentedString(totalPassedTests)).append("\n");
    sb.append("    totalFailedTests: ").append(toIndentedString(totalFailedTests)).append("\n");
    sb.append("    totalErrorTests: ").append(toIndentedString(totalErrorTests)).append("\n");
    sb.append("    totalIncompleteTests: ").append(toIndentedString(totalIncompleteTests)).append("\n");
    sb.append("    totalDiffTests: ").append(toIndentedString(totalDiffTests)).append("\n");
    sb.append("    totalDiffPassedTests: ").append(toIndentedString(totalDiffPassedTests)).append("\n");
    sb.append("    totalDiffFailedTests: ").append(toIndentedString(totalDiffFailedTests)).append("\n");
    sb.append("    totalDiffErrorTests: ").append(toIndentedString(totalDiffErrorTests)).append("\n");
    sb.append("    totalDiffIncompleteTests: ").append(toIndentedString(totalDiffIncompleteTests)).append("\n");
    sb.append("    executionId: ").append(toIndentedString(executionId)).append("\n");
    sb.append("    executionOrder: ").append(toIndentedString(executionOrder)).append("\n");
    sb.append("    testCaseId: ").append(toIndentedString(testCaseId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
