/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.core.web.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * ExternalProjectResource
 */


public class ExternalProjectResource {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("externalProjectId")
  private String externalProjectId = null;

  @JsonProperty("externalProjectKey")
  private String externalProjectKey = null;

  @JsonProperty("name")
  private String name = null;

  public ExternalProjectResource id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ExternalProjectResource externalProjectId(String externalProjectId) {
    this.externalProjectId = externalProjectId;
    return this;
  }

   /**
   * Get externalProjectId
   * @return externalProjectId
  **/
  @Schema(description = "")
  public String getExternalProjectId() {
    return externalProjectId;
  }

  public void setExternalProjectId(String externalProjectId) {
    this.externalProjectId = externalProjectId;
  }

  public ExternalProjectResource externalProjectKey(String externalProjectKey) {
    this.externalProjectKey = externalProjectKey;
    return this;
  }

   /**
   * Get externalProjectKey
   * @return externalProjectKey
  **/
  @Schema(description = "")
  public String getExternalProjectKey() {
    return externalProjectKey;
  }

  public void setExternalProjectKey(String externalProjectKey) {
    this.externalProjectKey = externalProjectKey;
  }

  public ExternalProjectResource name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalProjectResource externalProjectResource = (ExternalProjectResource) o;
    return Objects.equals(this.id, externalProjectResource.id) &&
        Objects.equals(this.externalProjectId, externalProjectResource.externalProjectId) &&
        Objects.equals(this.externalProjectKey, externalProjectResource.externalProjectKey) &&
        Objects.equals(this.name, externalProjectResource.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, externalProjectId, externalProjectKey, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalProjectResource {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    externalProjectId: ").append(toIndentedString(externalProjectId)).append("\n");
    sb.append("    externalProjectKey: ").append(toIndentedString(externalProjectKey)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
