/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.core.web.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * IncidentResource
 */


public class IncidentResource {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("projectId")
  private Long projectId = null;

  @JsonProperty("teamId")
  private Long teamId = null;

  @JsonProperty("urlIds")
  private List<String> urlIds = null;

  @JsonProperty("executionTestResultIds")
  private List<Long> executionTestResultIds = null;

  @JsonProperty("order")
  private Long order = null;

  @JsonProperty("createdAt")
  private OffsetDateTime createdAt = null;

  @JsonProperty("updatedAt")
  private OffsetDateTime updatedAt = null;

  public IncidentResource id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public IncidentResource name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IncidentResource description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public IncidentResource projectId(Long projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @Schema(description = "")
  public Long getProjectId() {
    return projectId;
  }

  public void setProjectId(Long projectId) {
    this.projectId = projectId;
  }

  public IncidentResource teamId(Long teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * Get teamId
   * @return teamId
  **/
  @Schema(description = "")
  public Long getTeamId() {
    return teamId;
  }

  public void setTeamId(Long teamId) {
    this.teamId = teamId;
  }

  public IncidentResource urlIds(List<String> urlIds) {
    this.urlIds = urlIds;
    return this;
  }

  public IncidentResource addUrlIdsItem(String urlIdsItem) {
    if (this.urlIds == null) {
      this.urlIds = new ArrayList<String>();
    }
    this.urlIds.add(urlIdsItem);
    return this;
  }

   /**
   * Get urlIds
   * @return urlIds
  **/
  @Schema(description = "")
  public List<String> getUrlIds() {
    return urlIds;
  }

  public void setUrlIds(List<String> urlIds) {
    this.urlIds = urlIds;
  }

  public IncidentResource executionTestResultIds(List<Long> executionTestResultIds) {
    this.executionTestResultIds = executionTestResultIds;
    return this;
  }

  public IncidentResource addExecutionTestResultIdsItem(Long executionTestResultIdsItem) {
    if (this.executionTestResultIds == null) {
      this.executionTestResultIds = new ArrayList<Long>();
    }
    this.executionTestResultIds.add(executionTestResultIdsItem);
    return this;
  }

   /**
   * Get executionTestResultIds
   * @return executionTestResultIds
  **/
  @Schema(description = "")
  public List<Long> getExecutionTestResultIds() {
    return executionTestResultIds;
  }

  public void setExecutionTestResultIds(List<Long> executionTestResultIds) {
    this.executionTestResultIds = executionTestResultIds;
  }

  public IncidentResource order(Long order) {
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @Schema(description = "")
  public Long getOrder() {
    return order;
  }

  public void setOrder(Long order) {
    this.order = order;
  }

  public IncidentResource createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public IncidentResource updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IncidentResource incidentResource = (IncidentResource) o;
    return Objects.equals(this.id, incidentResource.id) &&
        Objects.equals(this.name, incidentResource.name) &&
        Objects.equals(this.description, incidentResource.description) &&
        Objects.equals(this.projectId, incidentResource.projectId) &&
        Objects.equals(this.teamId, incidentResource.teamId) &&
        Objects.equals(this.urlIds, incidentResource.urlIds) &&
        Objects.equals(this.executionTestResultIds, incidentResource.executionTestResultIds) &&
        Objects.equals(this.order, incidentResource.order) &&
        Objects.equals(this.createdAt, incidentResource.createdAt) &&
        Objects.equals(this.updatedAt, incidentResource.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, projectId, teamId, urlIds, executionTestResultIds, order, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IncidentResource {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    urlIds: ").append(toIndentedString(urlIds)).append("\n");
    sb.append("    executionTestResultIds: ").append(toIndentedString(executionTestResultIds)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
