/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.core.web.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * OrganizationFeatureFlagResource
 */


public class OrganizationFeatureFlagResource {
  @JsonProperty("organizationId")
  private Long organizationId = null;

  @JsonProperty("subDomain")
  private Boolean subDomain = null;

  @JsonProperty("strictDomain")
  private Boolean strictDomain = null;

  @JsonProperty("sso")
  private Boolean sso = null;

  @JsonProperty("circleCi")
  private Boolean circleCi = null;

  public OrganizationFeatureFlagResource organizationId(Long organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @Schema(description = "")
  public Long getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(Long organizationId) {
    this.organizationId = organizationId;
  }

  public OrganizationFeatureFlagResource subDomain(Boolean subDomain) {
    this.subDomain = subDomain;
    return this;
  }

   /**
   * Get subDomain
   * @return subDomain
  **/
  @Schema(description = "")
  public Boolean isSubDomain() {
    return subDomain;
  }

  public void setSubDomain(Boolean subDomain) {
    this.subDomain = subDomain;
  }

  public OrganizationFeatureFlagResource strictDomain(Boolean strictDomain) {
    this.strictDomain = strictDomain;
    return this;
  }

   /**
   * Get strictDomain
   * @return strictDomain
  **/
  @Schema(description = "")
  public Boolean isStrictDomain() {
    return strictDomain;
  }

  public void setStrictDomain(Boolean strictDomain) {
    this.strictDomain = strictDomain;
  }

  public OrganizationFeatureFlagResource sso(Boolean sso) {
    this.sso = sso;
    return this;
  }

   /**
   * Get sso
   * @return sso
  **/
  @Schema(description = "")
  public Boolean isSso() {
    return sso;
  }

  public void setSso(Boolean sso) {
    this.sso = sso;
  }

  public OrganizationFeatureFlagResource circleCi(Boolean circleCi) {
    this.circleCi = circleCi;
    return this;
  }

   /**
   * Get circleCi
   * @return circleCi
  **/
  @Schema(description = "")
  public Boolean isCircleCi() {
    return circleCi;
  }

  public void setCircleCi(Boolean circleCi) {
    this.circleCi = circleCi;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationFeatureFlagResource organizationFeatureFlagResource = (OrganizationFeatureFlagResource) o;
    return Objects.equals(this.organizationId, organizationFeatureFlagResource.organizationId) &&
        Objects.equals(this.subDomain, organizationFeatureFlagResource.subDomain) &&
        Objects.equals(this.strictDomain, organizationFeatureFlagResource.strictDomain) &&
        Objects.equals(this.sso, organizationFeatureFlagResource.sso) &&
        Objects.equals(this.circleCi, organizationFeatureFlagResource.circleCi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organizationId, subDomain, strictDomain, sso, circleCi);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationFeatureFlagResource {\n");

    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    subDomain: ").append(toIndentedString(subDomain)).append("\n");
    sb.append("    strictDomain: ").append(toIndentedString(strictDomain)).append("\n");
    sb.append("    sso: ").append(toIndentedString(sso)).append("\n");
    sb.append("    circleCi: ").append(toIndentedString(circleCi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
