/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.core.web.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * OrganizationResource
 */


public class OrganizationResource {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  /**
   * Gets or Sets role
   */
  public enum RoleEnum {
    OWNER("OWNER"),
    ADMIN("ADMIN"),
    USER("USER"),
    BILLING_MANAGER("BILLING_MANAGER");

    private String value;

    RoleEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static RoleEnum fromValue(String text) {
      for (RoleEnum b : RoleEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("role")
  private RoleEnum role = null;

  @JsonProperty("orgFeatureFlag")
  private OrganizationFeatureFlagResource orgFeatureFlag = null;

  @JsonProperty("quotaKSE")
  private Long quotaKSE = null;

  @JsonProperty("machineQuotaKSE")
  private Long machineQuotaKSE = null;

  @JsonProperty("quotaEngine")
  private Long quotaEngine = null;

  @JsonProperty("machineQuotaEngine")
  private Long machineQuotaEngine = null;

  @JsonProperty("usedKSE")
  private Long usedKSE = null;

  @JsonProperty("usedEngine")
  private Long usedEngine = null;

  @JsonProperty("quotaTestOps")
  private Long quotaTestOps = null;

  @JsonProperty("usedTestOps")
  private Long usedTestOps = null;

  @JsonProperty("numberUser")
  private Long numberUser = null;

  @JsonProperty("quotaFloatingEngine")
  private Long quotaFloatingEngine = null;

  @JsonProperty("usedFloatingEngine")
  private Long usedFloatingEngine = null;

  @JsonProperty("canCreateOfflineKSE")
  private Boolean canCreateOfflineKSE = null;

  @JsonProperty("canCreateOfflineRE")
  private Boolean canCreateOfflineRE = null;

  @JsonProperty("subscriptionExpiryDateEngine")
  private OffsetDateTime subscriptionExpiryDateEngine = null;

  @JsonProperty("subscriptionExpiryDateKSE")
  private OffsetDateTime subscriptionExpiryDateKSE = null;

  @JsonProperty("subscriptionExpiryDateFloatingEngine")
  private OffsetDateTime subscriptionExpiryDateFloatingEngine = null;

  @JsonProperty("subscriptionExpiryDateTestOps")
  private OffsetDateTime subscriptionExpiryDateTestOps = null;

  @JsonProperty("subscribed")
  private Boolean subscribed = null;

  @JsonProperty("ksePaygo")
  private Boolean ksePaygo = null;

  @JsonProperty("krePaygo")
  private Boolean krePaygo = null;

  @JsonProperty("paygoQuota")
  private Long paygoQuota = null;

  @JsonProperty("domain")
  private String domain = null;

  @JsonProperty("subdomainUrl")
  private String subdomainUrl = null;

  @JsonProperty("strictDomain")
  private Boolean strictDomain = null;

  @JsonProperty("logoUrl")
  private String logoUrl = null;

  @JsonProperty("samlSSO")
  private Boolean samlSSO = null;

  @JsonProperty("kreLicense")
  private Boolean kreLicense = null;

  /**
   * Gets or Sets testOpsPackage
   */
  public enum TestOpsPackageEnum {
    BASIC("BASIC"),
    ADVANCED("ADVANCED"),
    ENTERPRISE("ENTERPRISE");

    private String value;

    TestOpsPackageEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TestOpsPackageEnum fromValue(String text) {
      for (TestOpsPackageEnum b : TestOpsPackageEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("testOpsPackage")
  private TestOpsPackageEnum testOpsPackage = null;

  /**
   * Gets or Sets testOpsBasicReason
   */
  public enum TestOpsBasicReasonEnum {
    USER("DISABLED_BY_USER"),
    ADMIN("DISABLED_BY_ADMIN");

    private String value;

    TestOpsBasicReasonEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TestOpsBasicReasonEnum fromValue(String text) {
      for (TestOpsBasicReasonEnum b : TestOpsBasicReasonEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("testOpsBasicReason")
  private TestOpsBasicReasonEnum testOpsBasicReason = null;

  public OrganizationResource id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public OrganizationResource name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OrganizationResource role(RoleEnum role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @Schema(description = "")
  public RoleEnum getRole() {
    return role;
  }

  public void setRole(RoleEnum role) {
    this.role = role;
  }

  public OrganizationResource orgFeatureFlag(OrganizationFeatureFlagResource orgFeatureFlag) {
    this.orgFeatureFlag = orgFeatureFlag;
    return this;
  }

   /**
   * Get orgFeatureFlag
   * @return orgFeatureFlag
  **/
  @Schema(description = "")
  public OrganizationFeatureFlagResource getOrgFeatureFlag() {
    return orgFeatureFlag;
  }

  public void setOrgFeatureFlag(OrganizationFeatureFlagResource orgFeatureFlag) {
    this.orgFeatureFlag = orgFeatureFlag;
  }

  public OrganizationResource quotaKSE(Long quotaKSE) {
    this.quotaKSE = quotaKSE;
    return this;
  }

   /**
   * Get quotaKSE
   * @return quotaKSE
  **/
  @Schema(description = "")
  public Long getQuotaKSE() {
    return quotaKSE;
  }

  public void setQuotaKSE(Long quotaKSE) {
    this.quotaKSE = quotaKSE;
  }

  public OrganizationResource machineQuotaKSE(Long machineQuotaKSE) {
    this.machineQuotaKSE = machineQuotaKSE;
    return this;
  }

   /**
   * Get machineQuotaKSE
   * @return machineQuotaKSE
  **/
  @Schema(description = "")
  public Long getMachineQuotaKSE() {
    return machineQuotaKSE;
  }

  public void setMachineQuotaKSE(Long machineQuotaKSE) {
    this.machineQuotaKSE = machineQuotaKSE;
  }

  public OrganizationResource quotaEngine(Long quotaEngine) {
    this.quotaEngine = quotaEngine;
    return this;
  }

   /**
   * Get quotaEngine
   * @return quotaEngine
  **/
  @Schema(description = "")
  public Long getQuotaEngine() {
    return quotaEngine;
  }

  public void setQuotaEngine(Long quotaEngine) {
    this.quotaEngine = quotaEngine;
  }

  public OrganizationResource machineQuotaEngine(Long machineQuotaEngine) {
    this.machineQuotaEngine = machineQuotaEngine;
    return this;
  }

   /**
   * Get machineQuotaEngine
   * @return machineQuotaEngine
  **/
  @Schema(description = "")
  public Long getMachineQuotaEngine() {
    return machineQuotaEngine;
  }

  public void setMachineQuotaEngine(Long machineQuotaEngine) {
    this.machineQuotaEngine = machineQuotaEngine;
  }

  public OrganizationResource usedKSE(Long usedKSE) {
    this.usedKSE = usedKSE;
    return this;
  }

   /**
   * Get usedKSE
   * @return usedKSE
  **/
  @Schema(description = "")
  public Long getUsedKSE() {
    return usedKSE;
  }

  public void setUsedKSE(Long usedKSE) {
    this.usedKSE = usedKSE;
  }

  public OrganizationResource usedEngine(Long usedEngine) {
    this.usedEngine = usedEngine;
    return this;
  }

   /**
   * Get usedEngine
   * @return usedEngine
  **/
  @Schema(description = "")
  public Long getUsedEngine() {
    return usedEngine;
  }

  public void setUsedEngine(Long usedEngine) {
    this.usedEngine = usedEngine;
  }

  public OrganizationResource quotaTestOps(Long quotaTestOps) {
    this.quotaTestOps = quotaTestOps;
    return this;
  }

   /**
   * Get quotaTestOps
   * @return quotaTestOps
  **/
  @Schema(description = "")
  public Long getQuotaTestOps() {
    return quotaTestOps;
  }

  public void setQuotaTestOps(Long quotaTestOps) {
    this.quotaTestOps = quotaTestOps;
  }

  public OrganizationResource usedTestOps(Long usedTestOps) {
    this.usedTestOps = usedTestOps;
    return this;
  }

   /**
   * Get usedTestOps
   * @return usedTestOps
  **/
  @Schema(description = "")
  public Long getUsedTestOps() {
    return usedTestOps;
  }

  public void setUsedTestOps(Long usedTestOps) {
    this.usedTestOps = usedTestOps;
  }

  public OrganizationResource numberUser(Long numberUser) {
    this.numberUser = numberUser;
    return this;
  }

   /**
   * Get numberUser
   * @return numberUser
  **/
  @Schema(description = "")
  public Long getNumberUser() {
    return numberUser;
  }

  public void setNumberUser(Long numberUser) {
    this.numberUser = numberUser;
  }

  public OrganizationResource quotaFloatingEngine(Long quotaFloatingEngine) {
    this.quotaFloatingEngine = quotaFloatingEngine;
    return this;
  }

   /**
   * Get quotaFloatingEngine
   * @return quotaFloatingEngine
  **/
  @Schema(description = "")
  public Long getQuotaFloatingEngine() {
    return quotaFloatingEngine;
  }

  public void setQuotaFloatingEngine(Long quotaFloatingEngine) {
    this.quotaFloatingEngine = quotaFloatingEngine;
  }

  public OrganizationResource usedFloatingEngine(Long usedFloatingEngine) {
    this.usedFloatingEngine = usedFloatingEngine;
    return this;
  }

   /**
   * Get usedFloatingEngine
   * @return usedFloatingEngine
  **/
  @Schema(description = "")
  public Long getUsedFloatingEngine() {
    return usedFloatingEngine;
  }

  public void setUsedFloatingEngine(Long usedFloatingEngine) {
    this.usedFloatingEngine = usedFloatingEngine;
  }

  public OrganizationResource canCreateOfflineKSE(Boolean canCreateOfflineKSE) {
    this.canCreateOfflineKSE = canCreateOfflineKSE;
    return this;
  }

   /**
   * Get canCreateOfflineKSE
   * @return canCreateOfflineKSE
  **/
  @Schema(description = "")
  public Boolean isCanCreateOfflineKSE() {
    return canCreateOfflineKSE;
  }

  public void setCanCreateOfflineKSE(Boolean canCreateOfflineKSE) {
    this.canCreateOfflineKSE = canCreateOfflineKSE;
  }

  public OrganizationResource canCreateOfflineRE(Boolean canCreateOfflineRE) {
    this.canCreateOfflineRE = canCreateOfflineRE;
    return this;
  }

   /**
   * Get canCreateOfflineRE
   * @return canCreateOfflineRE
  **/
  @Schema(description = "")
  public Boolean isCanCreateOfflineRE() {
    return canCreateOfflineRE;
  }

  public void setCanCreateOfflineRE(Boolean canCreateOfflineRE) {
    this.canCreateOfflineRE = canCreateOfflineRE;
  }

  public OrganizationResource subscriptionExpiryDateEngine(OffsetDateTime subscriptionExpiryDateEngine) {
    this.subscriptionExpiryDateEngine = subscriptionExpiryDateEngine;
    return this;
  }

   /**
   * Get subscriptionExpiryDateEngine
   * @return subscriptionExpiryDateEngine
  **/
  @Schema(description = "")
  public OffsetDateTime getSubscriptionExpiryDateEngine() {
    return subscriptionExpiryDateEngine;
  }

  public void setSubscriptionExpiryDateEngine(OffsetDateTime subscriptionExpiryDateEngine) {
    this.subscriptionExpiryDateEngine = subscriptionExpiryDateEngine;
  }

  public OrganizationResource subscriptionExpiryDateKSE(OffsetDateTime subscriptionExpiryDateKSE) {
    this.subscriptionExpiryDateKSE = subscriptionExpiryDateKSE;
    return this;
  }

   /**
   * Get subscriptionExpiryDateKSE
   * @return subscriptionExpiryDateKSE
  **/
  @Schema(description = "")
  public OffsetDateTime getSubscriptionExpiryDateKSE() {
    return subscriptionExpiryDateKSE;
  }

  public void setSubscriptionExpiryDateKSE(OffsetDateTime subscriptionExpiryDateKSE) {
    this.subscriptionExpiryDateKSE = subscriptionExpiryDateKSE;
  }

  public OrganizationResource subscriptionExpiryDateFloatingEngine(OffsetDateTime subscriptionExpiryDateFloatingEngine) {
    this.subscriptionExpiryDateFloatingEngine = subscriptionExpiryDateFloatingEngine;
    return this;
  }

   /**
   * Get subscriptionExpiryDateFloatingEngine
   * @return subscriptionExpiryDateFloatingEngine
  **/
  @Schema(description = "")
  public OffsetDateTime getSubscriptionExpiryDateFloatingEngine() {
    return subscriptionExpiryDateFloatingEngine;
  }

  public void setSubscriptionExpiryDateFloatingEngine(OffsetDateTime subscriptionExpiryDateFloatingEngine) {
    this.subscriptionExpiryDateFloatingEngine = subscriptionExpiryDateFloatingEngine;
  }

  public OrganizationResource subscriptionExpiryDateTestOps(OffsetDateTime subscriptionExpiryDateTestOps) {
    this.subscriptionExpiryDateTestOps = subscriptionExpiryDateTestOps;
    return this;
  }

   /**
   * Get subscriptionExpiryDateTestOps
   * @return subscriptionExpiryDateTestOps
  **/
  @Schema(description = "")
  public OffsetDateTime getSubscriptionExpiryDateTestOps() {
    return subscriptionExpiryDateTestOps;
  }

  public void setSubscriptionExpiryDateTestOps(OffsetDateTime subscriptionExpiryDateTestOps) {
    this.subscriptionExpiryDateTestOps = subscriptionExpiryDateTestOps;
  }

  public OrganizationResource subscribed(Boolean subscribed) {
    this.subscribed = subscribed;
    return this;
  }

   /**
   * Get subscribed
   * @return subscribed
  **/
  @Schema(description = "")
  public Boolean isSubscribed() {
    return subscribed;
  }

  public void setSubscribed(Boolean subscribed) {
    this.subscribed = subscribed;
  }

  public OrganizationResource ksePaygo(Boolean ksePaygo) {
    this.ksePaygo = ksePaygo;
    return this;
  }

   /**
   * Get ksePaygo
   * @return ksePaygo
  **/
  @Schema(description = "")
  public Boolean isKsePaygo() {
    return ksePaygo;
  }

  public void setKsePaygo(Boolean ksePaygo) {
    this.ksePaygo = ksePaygo;
  }

  public OrganizationResource krePaygo(Boolean krePaygo) {
    this.krePaygo = krePaygo;
    return this;
  }

   /**
   * Get krePaygo
   * @return krePaygo
  **/
  @Schema(description = "")
  public Boolean isKrePaygo() {
    return krePaygo;
  }

  public void setKrePaygo(Boolean krePaygo) {
    this.krePaygo = krePaygo;
  }

  public OrganizationResource paygoQuota(Long paygoQuota) {
    this.paygoQuota = paygoQuota;
    return this;
  }

   /**
   * Get paygoQuota
   * @return paygoQuota
  **/
  @Schema(description = "")
  public Long getPaygoQuota() {
    return paygoQuota;
  }

  public void setPaygoQuota(Long paygoQuota) {
    this.paygoQuota = paygoQuota;
  }

  public OrganizationResource domain(String domain) {
    this.domain = domain;
    return this;
  }

   /**
   * Get domain
   * @return domain
  **/
  @Schema(description = "")
  public String getDomain() {
    return domain;
  }

  public void setDomain(String domain) {
    this.domain = domain;
  }

  public OrganizationResource subdomainUrl(String subdomainUrl) {
    this.subdomainUrl = subdomainUrl;
    return this;
  }

   /**
   * Get subdomainUrl
   * @return subdomainUrl
  **/
  @Schema(description = "")
  public String getSubdomainUrl() {
    return subdomainUrl;
  }

  public void setSubdomainUrl(String subdomainUrl) {
    this.subdomainUrl = subdomainUrl;
  }

  public OrganizationResource strictDomain(Boolean strictDomain) {
    this.strictDomain = strictDomain;
    return this;
  }

   /**
   * Get strictDomain
   * @return strictDomain
  **/
  @Schema(description = "")
  public Boolean isStrictDomain() {
    return strictDomain;
  }

  public void setStrictDomain(Boolean strictDomain) {
    this.strictDomain = strictDomain;
  }

  public OrganizationResource logoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
    return this;
  }

   /**
   * Get logoUrl
   * @return logoUrl
  **/
  @Schema(description = "")
  public String getLogoUrl() {
    return logoUrl;
  }

  public void setLogoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
  }

  public OrganizationResource samlSSO(Boolean samlSSO) {
    this.samlSSO = samlSSO;
    return this;
  }

   /**
   * Get samlSSO
   * @return samlSSO
  **/
  @Schema(description = "")
  public Boolean isSamlSSO() {
    return samlSSO;
  }

  public void setSamlSSO(Boolean samlSSO) {
    this.samlSSO = samlSSO;
  }

  public OrganizationResource kreLicense(Boolean kreLicense) {
    this.kreLicense = kreLicense;
    return this;
  }

   /**
   * Get kreLicense
   * @return kreLicense
  **/
  @Schema(description = "")
  public Boolean isKreLicense() {
    return kreLicense;
  }

  public void setKreLicense(Boolean kreLicense) {
    this.kreLicense = kreLicense;
  }

  public OrganizationResource testOpsPackage(TestOpsPackageEnum testOpsPackage) {
    this.testOpsPackage = testOpsPackage;
    return this;
  }

   /**
   * Get testOpsPackage
   * @return testOpsPackage
  **/
  @Schema(description = "")
  public TestOpsPackageEnum getTestOpsPackage() {
    return testOpsPackage;
  }

  public void setTestOpsPackage(TestOpsPackageEnum testOpsPackage) {
    this.testOpsPackage = testOpsPackage;
  }

  public OrganizationResource testOpsBasicReason(TestOpsBasicReasonEnum testOpsBasicReason) {
    this.testOpsBasicReason = testOpsBasicReason;
    return this;
  }

   /**
   * Get testOpsBasicReason
   * @return testOpsBasicReason
  **/
  @Schema(description = "")
  public TestOpsBasicReasonEnum getTestOpsBasicReason() {
    return testOpsBasicReason;
  }

  public void setTestOpsBasicReason(TestOpsBasicReasonEnum testOpsBasicReason) {
    this.testOpsBasicReason = testOpsBasicReason;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationResource organizationResource = (OrganizationResource) o;
    return Objects.equals(this.id, organizationResource.id) &&
        Objects.equals(this.name, organizationResource.name) &&
        Objects.equals(this.role, organizationResource.role) &&
        Objects.equals(this.orgFeatureFlag, organizationResource.orgFeatureFlag) &&
        Objects.equals(this.quotaKSE, organizationResource.quotaKSE) &&
        Objects.equals(this.machineQuotaKSE, organizationResource.machineQuotaKSE) &&
        Objects.equals(this.quotaEngine, organizationResource.quotaEngine) &&
        Objects.equals(this.machineQuotaEngine, organizationResource.machineQuotaEngine) &&
        Objects.equals(this.usedKSE, organizationResource.usedKSE) &&
        Objects.equals(this.usedEngine, organizationResource.usedEngine) &&
        Objects.equals(this.quotaTestOps, organizationResource.quotaTestOps) &&
        Objects.equals(this.usedTestOps, organizationResource.usedTestOps) &&
        Objects.equals(this.numberUser, organizationResource.numberUser) &&
        Objects.equals(this.quotaFloatingEngine, organizationResource.quotaFloatingEngine) &&
        Objects.equals(this.usedFloatingEngine, organizationResource.usedFloatingEngine) &&
        Objects.equals(this.canCreateOfflineKSE, organizationResource.canCreateOfflineKSE) &&
        Objects.equals(this.canCreateOfflineRE, organizationResource.canCreateOfflineRE) &&
        Objects.equals(this.subscriptionExpiryDateEngine, organizationResource.subscriptionExpiryDateEngine) &&
        Objects.equals(this.subscriptionExpiryDateKSE, organizationResource.subscriptionExpiryDateKSE) &&
        Objects.equals(this.subscriptionExpiryDateFloatingEngine, organizationResource.subscriptionExpiryDateFloatingEngine) &&
        Objects.equals(this.subscriptionExpiryDateTestOps, organizationResource.subscriptionExpiryDateTestOps) &&
        Objects.equals(this.subscribed, organizationResource.subscribed) &&
        Objects.equals(this.ksePaygo, organizationResource.ksePaygo) &&
        Objects.equals(this.krePaygo, organizationResource.krePaygo) &&
        Objects.equals(this.paygoQuota, organizationResource.paygoQuota) &&
        Objects.equals(this.domain, organizationResource.domain) &&
        Objects.equals(this.subdomainUrl, organizationResource.subdomainUrl) &&
        Objects.equals(this.strictDomain, organizationResource.strictDomain) &&
        Objects.equals(this.logoUrl, organizationResource.logoUrl) &&
        Objects.equals(this.samlSSO, organizationResource.samlSSO) &&
        Objects.equals(this.kreLicense, organizationResource.kreLicense) &&
        Objects.equals(this.testOpsPackage, organizationResource.testOpsPackage) &&
        Objects.equals(this.testOpsBasicReason, organizationResource.testOpsBasicReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, role, orgFeatureFlag, quotaKSE, machineQuotaKSE, quotaEngine, machineQuotaEngine, usedKSE, usedEngine, quotaTestOps, usedTestOps, numberUser, quotaFloatingEngine, usedFloatingEngine, canCreateOfflineKSE, canCreateOfflineRE, subscriptionExpiryDateEngine, subscriptionExpiryDateKSE, subscriptionExpiryDateFloatingEngine, subscriptionExpiryDateTestOps, subscribed, ksePaygo, krePaygo, paygoQuota, domain, subdomainUrl, strictDomain, logoUrl, samlSSO, kreLicense, testOpsPackage, testOpsBasicReason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationResource {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    orgFeatureFlag: ").append(toIndentedString(orgFeatureFlag)).append("\n");
    sb.append("    quotaKSE: ").append(toIndentedString(quotaKSE)).append("\n");
    sb.append("    machineQuotaKSE: ").append(toIndentedString(machineQuotaKSE)).append("\n");
    sb.append("    quotaEngine: ").append(toIndentedString(quotaEngine)).append("\n");
    sb.append("    machineQuotaEngine: ").append(toIndentedString(machineQuotaEngine)).append("\n");
    sb.append("    usedKSE: ").append(toIndentedString(usedKSE)).append("\n");
    sb.append("    usedEngine: ").append(toIndentedString(usedEngine)).append("\n");
    sb.append("    quotaTestOps: ").append(toIndentedString(quotaTestOps)).append("\n");
    sb.append("    usedTestOps: ").append(toIndentedString(usedTestOps)).append("\n");
    sb.append("    numberUser: ").append(toIndentedString(numberUser)).append("\n");
    sb.append("    quotaFloatingEngine: ").append(toIndentedString(quotaFloatingEngine)).append("\n");
    sb.append("    usedFloatingEngine: ").append(toIndentedString(usedFloatingEngine)).append("\n");
    sb.append("    canCreateOfflineKSE: ").append(toIndentedString(canCreateOfflineKSE)).append("\n");
    sb.append("    canCreateOfflineRE: ").append(toIndentedString(canCreateOfflineRE)).append("\n");
    sb.append("    subscriptionExpiryDateEngine: ").append(toIndentedString(subscriptionExpiryDateEngine)).append("\n");
    sb.append("    subscriptionExpiryDateKSE: ").append(toIndentedString(subscriptionExpiryDateKSE)).append("\n");
    sb.append("    subscriptionExpiryDateFloatingEngine: ").append(toIndentedString(subscriptionExpiryDateFloatingEngine)).append("\n");
    sb.append("    subscriptionExpiryDateTestOps: ").append(toIndentedString(subscriptionExpiryDateTestOps)).append("\n");
    sb.append("    subscribed: ").append(toIndentedString(subscribed)).append("\n");
    sb.append("    ksePaygo: ").append(toIndentedString(ksePaygo)).append("\n");
    sb.append("    krePaygo: ").append(toIndentedString(krePaygo)).append("\n");
    sb.append("    paygoQuota: ").append(toIndentedString(paygoQuota)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    subdomainUrl: ").append(toIndentedString(subdomainUrl)).append("\n");
    sb.append("    strictDomain: ").append(toIndentedString(strictDomain)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("    samlSSO: ").append(toIndentedString(samlSSO)).append("\n");
    sb.append("    kreLicense: ").append(toIndentedString(kreLicense)).append("\n");
    sb.append("    testOpsPackage: ").append(toIndentedString(testOpsPackage)).append("\n");
    sb.append("    testOpsBasicReason: ").append(toIndentedString(testOpsBasicReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
