/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.core.web.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * ProjectSettingResource
 */


public class ProjectSettingResource {
  @JsonProperty("projectId")
  private Long projectId = null;

  @JsonProperty("bdd")
  private Boolean bdd = null;

  public ProjectSettingResource projectId(Long projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @Schema(description = "")
  public Long getProjectId() {
    return projectId;
  }

  public void setProjectId(Long projectId) {
    this.projectId = projectId;
  }

  public ProjectSettingResource bdd(Boolean bdd) {
    this.bdd = bdd;
    return this;
  }

   /**
   * Get bdd
   * @return bdd
  **/
  @Schema(description = "")
  public Boolean isBdd() {
    return bdd;
  }

  public void setBdd(Boolean bdd) {
    this.bdd = bdd;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectSettingResource projectSettingResource = (ProjectSettingResource) o;
    return Objects.equals(this.projectId, projectSettingResource.projectId) &&
        Objects.equals(this.bdd, projectSettingResource.bdd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, bdd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectSettingResource {\n");

    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    bdd: ").append(toIndentedString(bdd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
