/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.core.web.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SearchRequestPagination
 */


public class SearchRequestPagination {
  @JsonProperty("page")
  private Integer page = null;

  @JsonProperty("size")
  private Integer size = null;

  @JsonProperty("sorts")
  private List<SearchRequestSortOrder> sorts = null;

  public SearchRequestPagination page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @Schema(description = "")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public SearchRequestPagination size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @Schema(description = "")
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public SearchRequestPagination sorts(List<SearchRequestSortOrder> sorts) {
    this.sorts = sorts;
    return this;
  }

  public SearchRequestPagination addSortsItem(SearchRequestSortOrder sortsItem) {
    if (this.sorts == null) {
      this.sorts = new ArrayList<SearchRequestSortOrder>();
    }
    this.sorts.add(sortsItem);
    return this;
  }

   /**
   * Get sorts
   * @return sorts
  **/
  @Schema(description = "")
  public List<SearchRequestSortOrder> getSorts() {
    return sorts;
  }

  public void setSorts(List<SearchRequestSortOrder> sorts) {
    this.sorts = sorts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchRequestPagination searchRequestPagination = (SearchRequestPagination) o;
    return Objects.equals(this.page, searchRequestPagination.page) &&
        Objects.equals(this.size, searchRequestPagination.size) &&
        Objects.equals(this.sorts, searchRequestPagination.sorts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(page, size, sorts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchRequestPagination {\n");

    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    sorts: ").append(toIndentedString(sorts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
