/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.core.web.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.*;

/**
 * SearchConfigResource
 */


public class SearchConfigResource {
  @JsonProperty("filterConfig")
  private Map<String, String> filterConfig = null;

  @JsonProperty("sortDefault")
  private List<String> sortDefault = null;

  @JsonProperty("sortConfig")
  private List<String> sortConfig = null;

  public SearchConfigResource filterConfig(Map<String, String> filterConfig) {
    this.filterConfig = filterConfig;
    return this;
  }

  public SearchConfigResource putFilterConfigItem(String key, String filterConfigItem) {
    if (this.filterConfig == null) {
      this.filterConfig = new HashMap<String, String>();
    }
    this.filterConfig.put(key, filterConfigItem);
    return this;
  }

   /**
   * Get filterConfig
   * @return filterConfig
  **/
  @Schema(description = "")
  public Map<String, String> getFilterConfig() {
    return filterConfig;
  }

  public void setFilterConfig(Map<String, String> filterConfig) {
    this.filterConfig = filterConfig;
  }

  public SearchConfigResource sortDefault(List<String> sortDefault) {
    this.sortDefault = sortDefault;
    return this;
  }

  public SearchConfigResource addSortDefaultItem(String sortDefaultItem) {
    if (this.sortDefault == null) {
      this.sortDefault = new ArrayList<String>();
    }
    this.sortDefault.add(sortDefaultItem);
    return this;
  }

   /**
   * Get sortDefault
   * @return sortDefault
  **/
  @Schema(description = "")
  public List<String> getSortDefault() {
    return sortDefault;
  }

  public void setSortDefault(List<String> sortDefault) {
    this.sortDefault = sortDefault;
  }

  public SearchConfigResource sortConfig(List<String> sortConfig) {
    this.sortConfig = sortConfig;
    return this;
  }

  public SearchConfigResource addSortConfigItem(String sortConfigItem) {
    if (this.sortConfig == null) {
      this.sortConfig = new ArrayList<String>();
    }
    this.sortConfig.add(sortConfigItem);
    return this;
  }

   /**
   * Get sortConfig
   * @return sortConfig
  **/
  @Schema(description = "")
  public List<String> getSortConfig() {
    return sortConfig;
  }

  public void setSortConfig(List<String> sortConfig) {
    this.sortConfig = sortConfig;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchConfigResource searchConfigResource = (SearchConfigResource) o;
    return Objects.equals(this.filterConfig, searchConfigResource.filterConfig) &&
        Objects.equals(this.sortDefault, searchConfigResource.sortDefault) &&
        Objects.equals(this.sortConfig, searchConfigResource.sortConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filterConfig, sortDefault, sortConfig);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchConfigResource {\n");

    sb.append("    filterConfig: ").append(toIndentedString(filterConfig)).append("\n");
    sb.append("    sortDefault: ").append(toIndentedString(sortDefault)).append("\n");
    sb.append("    sortConfig: ").append(toIndentedString(sortConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
