/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.core.web.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * TestProjectResource
 */


public class TestProjectResource {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("uploadFileId")
  private Long uploadFileId = null;

  @JsonProperty("projectId")
  private Long projectId = null;

  @JsonProperty("teamId")
  private Long teamId = null;

  @JsonProperty("createdAt")
  private OffsetDateTime createdAt = null;

  @JsonProperty("latestJob")
  private JobResource latestJob = null;

  @JsonProperty("uploadFileName")
  private String uploadFileName = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    KS("KS"),
    GIT("GIT");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("gitRepository")
  private GitRepositoryResource gitRepository = null;

  @JsonProperty("testSuiteCollections")
  private List<TestSuiteCollectionResource> testSuiteCollections = null;

  public TestProjectResource id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public TestProjectResource name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TestProjectResource description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TestProjectResource uploadFileId(Long uploadFileId) {
    this.uploadFileId = uploadFileId;
    return this;
  }

   /**
   * Get uploadFileId
   * @return uploadFileId
  **/
  @Schema(description = "")
  public Long getUploadFileId() {
    return uploadFileId;
  }

  public void setUploadFileId(Long uploadFileId) {
    this.uploadFileId = uploadFileId;
  }

  public TestProjectResource projectId(Long projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @Schema(description = "")
  public Long getProjectId() {
    return projectId;
  }

  public void setProjectId(Long projectId) {
    this.projectId = projectId;
  }

  public TestProjectResource teamId(Long teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * Get teamId
   * @return teamId
  **/
  @Schema(description = "")
  public Long getTeamId() {
    return teamId;
  }

  public void setTeamId(Long teamId) {
    this.teamId = teamId;
  }

  public TestProjectResource createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public TestProjectResource latestJob(JobResource latestJob) {
    this.latestJob = latestJob;
    return this;
  }

   /**
   * Get latestJob
   * @return latestJob
  **/
  @Schema(description = "")
  public JobResource getLatestJob() {
    return latestJob;
  }

  public void setLatestJob(JobResource latestJob) {
    this.latestJob = latestJob;
  }

  public TestProjectResource uploadFileName(String uploadFileName) {
    this.uploadFileName = uploadFileName;
    return this;
  }

   /**
   * Get uploadFileName
   * @return uploadFileName
  **/
  @Schema(description = "")
  public String getUploadFileName() {
    return uploadFileName;
  }

  public void setUploadFileName(String uploadFileName) {
    this.uploadFileName = uploadFileName;
  }

  public TestProjectResource type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public TestProjectResource gitRepository(GitRepositoryResource gitRepository) {
    this.gitRepository = gitRepository;
    return this;
  }

   /**
   * Get gitRepository
   * @return gitRepository
  **/
  @Schema(description = "")
  public GitRepositoryResource getGitRepository() {
    return gitRepository;
  }

  public void setGitRepository(GitRepositoryResource gitRepository) {
    this.gitRepository = gitRepository;
  }

  public TestProjectResource testSuiteCollections(List<TestSuiteCollectionResource> testSuiteCollections) {
    this.testSuiteCollections = testSuiteCollections;
    return this;
  }

  public TestProjectResource addTestSuiteCollectionsItem(TestSuiteCollectionResource testSuiteCollectionsItem) {
    if (this.testSuiteCollections == null) {
      this.testSuiteCollections = new ArrayList<TestSuiteCollectionResource>();
    }
    this.testSuiteCollections.add(testSuiteCollectionsItem);
    return this;
  }

   /**
   * Get testSuiteCollections
   * @return testSuiteCollections
  **/
  @Schema(description = "")
  public List<TestSuiteCollectionResource> getTestSuiteCollections() {
    return testSuiteCollections;
  }

  public void setTestSuiteCollections(List<TestSuiteCollectionResource> testSuiteCollections) {
    this.testSuiteCollections = testSuiteCollections;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestProjectResource testProjectResource = (TestProjectResource) o;
    return Objects.equals(this.id, testProjectResource.id) &&
        Objects.equals(this.name, testProjectResource.name) &&
        Objects.equals(this.description, testProjectResource.description) &&
        Objects.equals(this.uploadFileId, testProjectResource.uploadFileId) &&
        Objects.equals(this.projectId, testProjectResource.projectId) &&
        Objects.equals(this.teamId, testProjectResource.teamId) &&
        Objects.equals(this.createdAt, testProjectResource.createdAt) &&
        Objects.equals(this.latestJob, testProjectResource.latestJob) &&
        Objects.equals(this.uploadFileName, testProjectResource.uploadFileName) &&
        Objects.equals(this.type, testProjectResource.type) &&
        Objects.equals(this.gitRepository, testProjectResource.gitRepository) &&
        Objects.equals(this.testSuiteCollections, testProjectResource.testSuiteCollections);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, uploadFileId, projectId, teamId, createdAt, latestJob, uploadFileName, type, gitRepository, testSuiteCollections);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestProjectResource {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    uploadFileId: ").append(toIndentedString(uploadFileId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    latestJob: ").append(toIndentedString(latestJob)).append("\n");
    sb.append("    uploadFileName: ").append(toIndentedString(uploadFileName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    gitRepository: ").append(toIndentedString(gitRepository)).append("\n");
    sb.append("    testSuiteCollections: ").append(toIndentedString(testSuiteCollections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
