/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.core.web.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * TimeZoneResourceOffsetRulesDurationUnits
 */


public class TimeZoneResourceOffsetRulesDurationUnits {
  @JsonProperty("dateBased")
  private Boolean dateBased = null;

  @JsonProperty("timeBased")
  private Boolean timeBased = null;

  @JsonProperty("durationEstimated")
  private Boolean durationEstimated = null;

  public TimeZoneResourceOffsetRulesDurationUnits dateBased(Boolean dateBased) {
    this.dateBased = dateBased;
    return this;
  }

   /**
   * Get dateBased
   * @return dateBased
  **/
  @Schema(description = "")
  public Boolean isDateBased() {
    return dateBased;
  }

  public void setDateBased(Boolean dateBased) {
    this.dateBased = dateBased;
  }

  public TimeZoneResourceOffsetRulesDurationUnits timeBased(Boolean timeBased) {
    this.timeBased = timeBased;
    return this;
  }

   /**
   * Get timeBased
   * @return timeBased
  **/
  @Schema(description = "")
  public Boolean isTimeBased() {
    return timeBased;
  }

  public void setTimeBased(Boolean timeBased) {
    this.timeBased = timeBased;
  }

  public TimeZoneResourceOffsetRulesDurationUnits durationEstimated(Boolean durationEstimated) {
    this.durationEstimated = durationEstimated;
    return this;
  }

   /**
   * Get durationEstimated
   * @return durationEstimated
  **/
  @Schema(description = "")
  public Boolean isDurationEstimated() {
    return durationEstimated;
  }

  public void setDurationEstimated(Boolean durationEstimated) {
    this.durationEstimated = durationEstimated;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeZoneResourceOffsetRulesDurationUnits timeZoneResourceOffsetRulesDurationUnits = (TimeZoneResourceOffsetRulesDurationUnits) o;
    return Objects.equals(this.dateBased, timeZoneResourceOffsetRulesDurationUnits.dateBased) &&
        Objects.equals(this.timeBased, timeZoneResourceOffsetRulesDurationUnits.timeBased) &&
        Objects.equals(this.durationEstimated, timeZoneResourceOffsetRulesDurationUnits.durationEstimated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateBased, timeBased, durationEstimated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeZoneResourceOffsetRulesDurationUnits {\n");

    sb.append("    dateBased: ").append(toIndentedString(dateBased)).append("\n");
    sb.append("    timeBased: ").append(toIndentedString(timeBased)).append("\n");
    sb.append("    durationEstimated: ").append(toIndentedString(durationEstimated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
