/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.core.web.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * TimeZoneResourceOffset
 */


public class TimeZoneResourceOffset {
  @JsonProperty("totalSeconds")
  private Integer totalSeconds = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("rules")
  private TimeZoneResourceOffsetRules rules = null;

  public TimeZoneResourceOffset totalSeconds(Integer totalSeconds) {
    this.totalSeconds = totalSeconds;
    return this;
  }

   /**
   * Get totalSeconds
   * @return totalSeconds
  **/
  @Schema(description = "")
  public Integer getTotalSeconds() {
    return totalSeconds;
  }

  public void setTotalSeconds(Integer totalSeconds) {
    this.totalSeconds = totalSeconds;
  }

  public TimeZoneResourceOffset id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TimeZoneResourceOffset rules(TimeZoneResourceOffsetRules rules) {
    this.rules = rules;
    return this;
  }

   /**
   * Get rules
   * @return rules
  **/
  @Schema(description = "")
  public TimeZoneResourceOffsetRules getRules() {
    return rules;
  }

  public void setRules(TimeZoneResourceOffsetRules rules) {
    this.rules = rules;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeZoneResourceOffset timeZoneResourceOffset = (TimeZoneResourceOffset) o;
    return Objects.equals(this.totalSeconds, timeZoneResourceOffset.totalSeconds) &&
        Objects.equals(this.id, timeZoneResourceOffset.id) &&
        Objects.equals(this.rules, timeZoneResourceOffset.rules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalSeconds, id, rules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeZoneResourceOffset {\n");

    sb.append("    totalSeconds: ").append(toIndentedString(totalSeconds)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
