/*
 * Katalon TestOps API reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.katalon.testops.core.web.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * UserOrganizationFeatureResource
 */


public class UserOrganizationFeatureResource {
  @JsonProperty("user")
  private UserResource user = null;

  @JsonProperty("userId")
  private Long userId = null;

  @JsonProperty("organizationId")
  private Long organizationId = null;

  @JsonProperty("userEmail")
  private String userEmail = null;

  @JsonProperty("organization")
  private OrganizationResource organization = null;

  /**
   * Gets or Sets feature
   */
  public enum FeatureEnum {
    KSE("KSE"),
    ENGINE("ENGINE"),
    TESTOPS("TESTOPS"),
    FLOATING_ENGINE("FLOATING_ENGINE"),
    UNLIMITED_KSE("UNLIMITED_KSE"),
    UNLIMITED_ENGINE("UNLIMITED_ENGINE");

    private String value;

    FeatureEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static FeatureEnum fromValue(String text) {
      for (FeatureEnum b : FeatureEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("feature")
  private FeatureEnum feature = null;

  public UserOrganizationFeatureResource user(UserResource user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @Schema(description = "")
  public UserResource getUser() {
    return user;
  }

  public void setUser(UserResource user) {
    this.user = user;
  }

  public UserOrganizationFeatureResource userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(description = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public UserOrganizationFeatureResource organizationId(Long organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @Schema(description = "")
  public Long getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(Long organizationId) {
    this.organizationId = organizationId;
  }

  public UserOrganizationFeatureResource userEmail(String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

   /**
   * Get userEmail
   * @return userEmail
  **/
  @Schema(description = "")
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public UserOrganizationFeatureResource organization(OrganizationResource organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  @Schema(description = "")
  public OrganizationResource getOrganization() {
    return organization;
  }

  public void setOrganization(OrganizationResource organization) {
    this.organization = organization;
  }

  public UserOrganizationFeatureResource feature(FeatureEnum feature) {
    this.feature = feature;
    return this;
  }

   /**
   * Get feature
   * @return feature
  **/
  @Schema(description = "")
  public FeatureEnum getFeature() {
    return feature;
  }

  public void setFeature(FeatureEnum feature) {
    this.feature = feature;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserOrganizationFeatureResource userOrganizationFeatureResource = (UserOrganizationFeatureResource) o;
    return Objects.equals(this.user, userOrganizationFeatureResource.user) &&
        Objects.equals(this.userId, userOrganizationFeatureResource.userId) &&
        Objects.equals(this.organizationId, userOrganizationFeatureResource.organizationId) &&
        Objects.equals(this.userEmail, userOrganizationFeatureResource.userEmail) &&
        Objects.equals(this.organization, userOrganizationFeatureResource.organization) &&
        Objects.equals(this.feature, userOrganizationFeatureResource.feature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user, userId, organizationId, userEmail, organization, feature);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserOrganizationFeatureResource {\n");

    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    feature: ").append(toIndentedString(feature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
